---
- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  gather_facts: yes
  tasks:
    - name: copying initialize.sh file
      ansible.builtin.copy:
        src: "/home/rp/ansible/ansible-kubernetes-deployment/{{ item }}"
        dest: /root/
        mode: '0700'
      loop:
        - initialize.sh
        - join-node.sh
      notify: 
        - Executing shell script

  handlers: 
    - name: Executing shell script
      ansible.builtin.shell: /root/initialize.sh
      become: yes
