---
- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  gather_facts: yes
  tasks:
    - name: copying initialize.sh file to Remote System
      ansible.builtin.copy:
        src: /home/jenkins/ansible-all/initialize.sh
        dest: /root/
        mode: '0700'
      notify: 
        - Executing Initialization script

  handlers: 
    - name: Executing Initialization script
      ansible.builtin.shell: /root/initialize.sh
      become: yes
