---
- name: Install kubernetes softwares
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Copying Software Installation file
      ansible.builtin.copy:
        src: /home/$USER/ansible-kubernetes-deployment/install-softwares.sh
        dest: /root/
        mode: '0700'
      notify: 
        - Executing Software Installation script

  handlers: 
    - name: Executing Software Installation script
      ansible.builtin.shell: /root/install-softwares.sh
      become: yes
