---
- name: Install kubernetes softwares
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: copy script.sh file
      ansible.builtin.copy:
        src: /home/jenkins/ansible-all/install-softwares.sh
        dest: /root/
        mode: '0700'
      notify: 
        - Executing shell script

  handlers: 
    - name: Executing shell script
      ansible.builtin.shell: /root/install-softwares.sh
      become: yes