---
- name: Join Managed nodes
  hosts: node
  become: yes
  gather_facts: yes
  tasks:
    - name: copying join-node.sh file
      ansible.builtin.copy:
        src: /home/$USER/ansible-kubernetes-deployment/join-node.sh
        dest: /root/
        mode: '0700'
      notify:
        - Executing join-node.sh script

  handlers:
    - name: Executing join-node.sh script
      ansible.builtin.shell: /root/join-node.sh
      become: yes
