---
- name: shutdown instances
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: print all the ansible gather facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: shutdown instances
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == "Debian"